### PR TITLE
V1.1.0

### PR DESCRIPTION
**Pull request by Timendus**
Support TI-84+SE and break API for matching calculators with files

### CODE REVIEW

**Comment by Timendus** [comment]
Haha, doesn't really matter :) This is more specific, I guess.

**Comment by adriweb** [comment]
I guess we'll have to figure out why `test/calculators/ti84p.test.js` fails before merging.

**Comment by adriweb** [comment]
Alright, LGTM code-wise and tests-wise, although I haven't actually checked for real with a calc.

**Review by adriweb — DISMISSED** [review]

**Comment by adriweb** [comment]
@debrouxl @tari would you be able to test?

**Comment by tari** [comment]
Seems to work with my 84PSE; was able to send a program to the device. Need to clean my 89Ti before I can test with that.

I did find that having TiLP configured on my Windows machine seems to interfere with making the calculator visible to WebUSB. I don't think there's anything that can be done about that, but it might be useful to document.

**Comment by debrouxl** [comment]
As usual, Windows driver limitations ruin the fun...
Did you install the libusb-win32 filter driver ?

**Comment by Timendus** [comment]
Alright, let's get this show back on the road! 😉 
Great to see you guys contributing! 🎉  Thanks for the test @tari!

I've created three issues that I think need fixing for a v1.1.0 release:

* #6 Code refactor on recording ordering
* #7 Make recordings versioned
* #8 Add tests for new calculator models

...and these probably also need to happen in that order 😄

We may want to split off the last issue (#8) in a (set of) other PRs, but we'll tackle that when we get there.

**Comment by Timendus** [comment]
I think I have an idea for adding all these untested calculator models. The API should enable the user to see what the level of support for each model is, and then decide if they want to allow it. Currently there's a function called `models` that just returns an array of names of "supported" calculators. That's a bit too binary. Let's make that either:

* `experimental` (hasn't been tested, may work)
* `beta` (has been known to work, but no automated test)
* `partial` (works, has an automated test, but not all functions are present / tested)
* `supported` (works, has an automated test)

I think there are basically two modes of operation for API consumers:
* Allow the user to only select calculators that are supported at level X
* Allow the user to select any Texas Instruments device, and then check to see what the support level is, and warn the user if needed

The second mode is possible if we add the level of support to the calculator objects. And also to the `models` function to inform the user beforehand.

The first mode requires a slight change in the `choose` API.

This version is going to break the API anyway, so this feels like the right moment to add this.

**Comment by adriweb** [comment]
That's not a bad idea :)
I believe people would want to try doing things even if it's not auto-tested though, so the default chosen level should probably be "beta", with a warning somewhere encouraging people to submit feedback and bug reports should they encounter one.

**Comment by adriweb** [comment]
For some reason, Travis' status is not reported back to here, but it's in fact OK, nice job for the new changes :)

**Comment by Timendus** [comment]
A couple of things have been done. These commits should fix #6 so CodeClimate is happy again (the remaining issues have to do with code duplication on the calculator definitions, which I find acceptable). Also, I have added some rudimentary support for having different support levels.

I have to make some changes to ticalc.link now so I can test if the support stuff works in a more realistic setting. And then finish #7.

**Pull request merged**
