### PR TITLE
Add all the calculator models Lionel mentioned

### PR DESCRIPTION
**Pull request by Timendus**

### CODE REVIEW

**Comment by adriweb** [comment]
"Color Edition" doesn't exist, it's just "CE".
Also, it's "CE Edition Python", for the 83PCEEP :)

**Comment by adriweb** [comment]
... and same for the 84+CSE, the official name is "TI-84 Plus C Silver Edition". Sure, C probably means Color, but that's not official :p

**Comment by Timendus** [comment]
How about I just give you access to this repository..? ;)

**Comment by adriweb** [comment]
Sure, you can add Lionel too.
And maybe jacobly0 I guess ? Maybe later idk :p

Thank you,
Adrien Bertrand

**Comment by tari** [comment]
This hasn't been touched in a while; does it need anything else before merging?

**Pull request merged**
